project:
  type: website

website:
  title: "R'tichoke"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: installation.qmd
        text: R Installation Guide
      - text: Get Started
        menu:
        - href: get-started/r-package-management.qmd
          text: Installing Packages
        - href: get-started/variables.qmd
          text: Variables in R
        - href: get-started/loops.qmd
          text: Loops and Apply Functions
        - href: get-started/indexing.qmd
          text: Indexing Arrays
        - href: get-started/reading-data.qmd
          text: Reading Data
        - href: get-started/dplyr.qmd
          text: Introduction to dplyr
        - href: get-started/data-table.qmd
          text: Introduction to data.table
        - href: get-started/base-graphics.qmd
          text: Base Graphics          
        - href: get-started/ggplot2.qmd
          text: ggplot2 Graphics
      - href: webr.qmd
        text: WebR Playground
      - text: Blog
        href: posts.qmd
      - href: about.qmd
        text: About
      - href: https://www.r-bloggers.com/
        text: R-Bloggers
      
  page-footer: 
    left: " 2025 R'tichoke"
    right: 
      - icon: github
        href: https://github.com
      - icon: twitter
        href: https://twitter.com

format:
  html:
    theme: sketchy
    highlight-style: zenburn
    toc: true
    code-copy: true
    code-tools: false
    css: styles.css
    
editor: source
